### ISSUE TITLE
Whatsapp Web Enabler on IOS6 :(

### ISSUE THREAD

**Issue by indapublic** [stonesam92/WhatsMac#3]
I don't know where I can leave my question, so I'm asking here.
I have jailbreaked IPhone 4 and IOS 6.1.3
I'm installed Whatsapp Web Enabler successfully. But when I tapped on it - Settings app crashed and closed.

Maybe, you know a reason of this behaviour?

Thank you in advance

**Comment by stonesam92** [comment]
Sorry, I have no idea how WhatsApp Web enabler does it's thing. 

According to Cydia, its maintained by iMokhles (imokhless0 **at** gmail.com), so he/she would probably be the best person to contact.
